# Configuration for librarian-puppet.
forge "http://forge.puppetlabs.com"
 
mod "puppetlabs/razor"
mod "puppetlabs/ntp", "0.0.3"
 
mod "apt",
   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
 
mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "nodejs",
    :git => "git://github.com/puppetlabs/puppetlabs-nodejs.git"